# Generated by Django 5.1.2 on 2024-12-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="attempt_limit",
        ),
        migrations.AddField(
            model_name="test",
            name="attempt_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
