# Generated by Django 5.1.2 on 2024-12-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "school_year",
            },
        ),
        migrations.CreateModel(
            name="StudentTest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_tests",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount_of_time", models.IntegerField()),
            ],
            options={
                "db_table": "tests",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("choice_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="accounts.question",
                    ),
                ),
            ],
            options={
                "db_table": "choices",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        db_column="school_year_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="accounts.schoolyear",
                    ),
                ),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="MonitoringData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                ("cheating_duration", models.IntegerField(blank=True, null=True)),
                ("switch_count", models.IntegerField(blank=True, null=True)),
                (
                    "student_test",
                    models.ForeignKey(
                        db_column="student_test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_data",
                        to="accounts.studenttest",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_data",
            },
        ),
        migrations.AddField(
            model_name="studenttest",
            name="test",
            field=models.ForeignKey(
                db_column="test_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tests",
                to="accounts.test",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                db_column="test_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="accounts.test",
            ),
        ),
        migrations.CreateModel(
            name="ClassTest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_id",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_tests",
                        to="accounts.class",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_tests",
                        to="accounts.test",
                    ),
                ),
            ],
            options={
                "db_table": "class_tests",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.BooleanField(blank=True, null=True)),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("attempt_limit", models.IntegerField(blank=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.AddField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="studenttest",
            name="student",
            field=models.ForeignKey(
                db_column="student_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tests",
                to="accounts.user",
            ),
        ),
        migrations.CreateModel(
            name="ClassUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_id",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_users",
                        to="accounts.class",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_users",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "class_users",
            },
        ),
    ]
